In [140]:
using LinearAlgebra

Compuerta Hadamar es

$$
H=\frac{1}{\sqrt{2}}
\left(\begin{array}{cc} 
1 & 1\\ 
1 & -1
\end{array}\right)
$$


In [157]:
H=1/sqrt(2)*[1 1; 1 -1] #Definimos la compuerta HAdamar
ϕ=1/sqrt(2)*[1, 1*im] #DEfinimos el cubit inicial

kb=[[1,0],[0,1]] #BASE USUAL

2-element Vector{Vector{Int64}}:
 [1, 0]
 [0, 1]

In [158]:
mutable struct PQ
    x::Int64
    q::Vector{ComplexF64}
end

In [159]:
qb=PQ(0,ϕ)
qq=PQ(0,[0,0])

PQ(0, ComplexF64[0.0 + 0.0im, 0.0 + 0.0im])

In [160]:
qb.x

0

In [161]:
Vector{PQ}

Vector{PQ} (alias for Array{PQ, 1})

In [162]:
n=7
P=2n+1 #n-1 es el número central


Pos=zeros(Int64, P) # Número de posiciones impar
A=Array{PQ}(undef, P) #Numero de vectores pos y quiralidad

15-element Vector{PQ}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef

In [163]:
@inbounds for i=1:P
    A[i]=qq
end;

In [164]:
A[n+1]=qb #El elemeno n-1 es el principio "central" [1|0>+i|1>] (X) |0x>

PQ(0, ComplexF64[0.7071067811865475 + 0.0im, 0.0 + 0.7071067811865475im])

In [165]:
H*A[n+1].q #Aplicamos Hadamar a la parte quiral |q1>=H|q0>

2-element Vector{ComplexF64}:
 0.4999999999999999 + 0.4999999999999999im
 0.4999999999999999 - 0.4999999999999999im

In [166]:
dot(kb[1],H*A[n+1].q) #este es el producto escalar <0|phi>
dot(kb[2],H*A[n+1].q)#este es el producto escalar <1|phi>

0.4999999999999999 - 0.4999999999999999im

In [167]:
a=kb[1]*transpose(kb[1])*H*A[n+1].q #La proyección del vector quiral  |0><0|H|q0>=|0><0|q1>


2-element Vector{ComplexF64}:
 0.4999999999999999 + 0.4999999999999999im
                0.0 + 0.0im

In [168]:
b=kb[2]*transpose(kb[2])*H*A[n+1].q #es diferente de 0 entonces  |1><1|H|q0>=|1><1|q1>

2-element Vector{ComplexF64}:
                0.0 + 0.0im
 0.4999999999999999 - 0.4999999999999999im

In [169]:
#A=Array{PQ}(undef, P) #Numero de vectores pos y quiralidad


In [170]:
#Como las proyecciones son diferente de cero 
A[(n+1)+1]=PQ(0+1,a)
A[(n+1)-1]=PQ(0-1,b)

PQ(-1, ComplexF64[0.0 + 0.0im, 0.4999999999999999 - 0.4999999999999999im])

In [176]:
A[1]==

LoadError: syntax: incomplete: premature end of input

In [128]:
eachindex(P)

Base.OneTo(1)